export enum SurveyAction {
  CREATE_SURVEY_INIT = "CREATE_SURVEY_INIT",
  CREATE_SURVEY_SUCCESS = "CREATE_SURVEY_SUCCESS",
  SURVEY_LIST_INIT = "SURVEY_LIST_INIT",
  SURVEY_LIST_SUCCESS = "SURVEY_LIST_SUCCESS",
}
